### ISSUE TITLE
EncryptWithAES

### ISSUE THREAD

**Issue by bthakks** [cisco/ASAssets_Utilities#21]
Not sure if its an issue or something I am not doing correctly! I imported the ASAssets in to the CIS 7.0.4, executed the retrospect all procedure successfully. But when I try to use the EncryptWithAES procedure it throws the error message around Exception with CISBaseCJP.invoke. Detail error message below 

com.compositesw.cdms.webapi.WebapiException: An exception occurred while invoking the custom procedure
    "/shared/ASAssets/Utilities/encoding/EncodingCJP/EncryptWithAES": CISBaseCJP.invoke
    (com.compositesw.extension.CustomProcedureException)  [cproc-1900005]
Cause: CISBaseCJP.invoke
	An exception occurred while invoking the custom procedure
    "/shared/ASAssets/Utilities/encoding/EncodingCJP/EncryptWithAES": CISBaseCJP.invoke
    (com.compositesw.extension.CustomProcedureException)  [cproc-1900005]
	at com.compositesw.server.customproc.CustomProcConnection.cprocEx(CustomProcConnection.java:120)
	at com.compositesw.server.customproc.cvt.ProcedureReference2ProcedureRequest.cprocEx(ProcedureReference2ProcedureRequest.java:643)
	at com.compositesw.server.customproc.cvt.ProcedureReference2ProcedureRequest.access$100(ProcedureReference2ProcedureRequest.java:49)
	at com.compositesw.server.customproc.cvt.ProcedureReference2ProcedureRequest$WorkUnitInvoke.invoke(ProcedureReference2ProcedureRequest.java:208)
	at com.compositesw.server.customproc.cvt.ProcedureReference2ProcedureRequest.invoke(ProcedureReference2ProcedureRequest.java:359)
	at com.compositesw.server.request.HookProcedureRequest.invoke(HookProcedureRequest.java:79)
	at com.compositesw.cdms.webapi.service.WProcResultImpl$InvokerThread.run(WProcResultImpl.java:755)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.compositesw.extension.CustomProcedureException: CISBaseCJP.invoke
	at com.cisco.dvbu.ps.utils.encoding.EncodingUtilTemplate.invoke(EncodingUtilTemplate.java:121)
	at com.compositesw.server.customproc.CustomProcCCLDecorator.invoke(CustomProcCCLDecorator.java:148)
	at com.compositesw.server.customproc.cvt.ProcedureReference2ProcedureRequest$WorkUnitInvoke.invoke(ProcedureReference2ProcedureRequest.java:204)
	... 6 more
Caused by: java.security.InvalidKeyException: Invalid AES key length: 18 bytes
	at com.sun.crypto.provider.AESCipher.engineGetKeySize(AESCipher.java:372)
	at javax.crypto.Cipher.passCryptoPermCheck(Cipher.java:1052)
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1023)
	at javax.crypto.Cipher.implInit(Cipher.java:790)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
	at javax.crypto.Cipher.init(Cipher.java:1348)
	at javax.crypto.Cipher.init(Cipher.java:1282)
	at com.cisco.dvbu.ps.utils.encoding.EncryptDecryptAES.encrypt(EncryptDecryptAES.java:36)
	at com.cisco.dvbu.ps.utils.encoding.EncryptWithAES.execute(EncryptWithAES.java:94)
	at com.cisco.dvbu.ps.utils.encoding.EncodingUtilTemplate.invoke(EncodingUtilTemplate.java:113)
	... 8 more

	at com.compositesw.cdms.webapi.WebapiException_SOAPSerializer.doDeserialize(WebapiException_SOAPSerializer.java:58)
	at com.sun.xml.rpc.encoding.ObjectSerializerBase.deserialize(ObjectSerializerBase.java:209)
	at com.sun.xml.rpc.encoding.ReferenceableSerializerImpl.deserialize(ReferenceableSerializerImpl.java:172)
	at com.compositesw.cdms.webapi.service.WMetaDataSvc_procresult_getOutputValues_Fault_SOAPSerializer.deserializeDetail(WMetaDataSvc_procresult_getOutputValues_Fault_SOAPSerializer.java:54)
	at com.sun.xml.rpc.encoding.SOAPFaultInfoSerializer.doDeserialize(SOAPFaultInfoSerializer.java:151)
	at com.sun.xml.rpc.encoding.ObjectSerializerBase.deserialize(ObjectSerializerBase.java:209)
	at com.sun.xml.rpc.encoding.ReferenceableSerializerImpl.deserialize(ReferenceableSerializerImpl.java:172)
	at com.compositesw.cdms.webapi.service.WMetaDataSvc_Stub._readBodyFaultElement(WMetaDataSvc_Stub.java:25180)
	at com.sun.xml.rpc.client.StreamingSender._send(StreamingSender.java:238)
	at com.compositesw.cdms.webapi.service.WMetaDataSvc_Stub.procresult_getOutputValues(WMetaDataSvc_Stub.java:15623)
	at com.compositesw.cdms.webapi.WProcResult.getOutputParameterCount(WProcResult.java:36)
	at com.compositesw.ui.modeler.view.result.ComplexProgressTasks$ComplexExecuteQueryTask.displayQueryResult(ComplexProgressTasks.java:511)
	at com.compositesw.ui.modeler.view.result.ComplexProgressTasks$ComplexExecuteQueryTask.executeQuery(ComplexProgressTasks.java:269)
	at com.compositesw.ui.modeler.view.result.ComplexProgressTasks$ComplexExecuteQueryTask.goWork(ComplexProgressTasks.java:129)
	at com.compositesw.ui.modeler.view.result.LongTask$1.run(LongTask.java:62)
	at java.lang.Thread.run(Unknown Source)

Version Information: Studio 7.0.4.00.01, Build ID Build: 58e9f86-2016-07-28, Server 7.0.4.00.01

**Comment by bthakks** [comment]
Ignore me, it was just me being silly. Error message was coming as I didn't pass the right length of the Key. Not sure how I delete the issue.
